steps:
  # ==========================================
  # FRONTEND BUILD & DEPLOY
  # ==========================================
  # 1. Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', './frontend']
    id: 'Build Frontend'

  # 2. Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend']
    id: 'Push Frontend'

  # 3. Deploy Frontend to Cloud Run
  # Dynamically fetches the backend URL from the deployed backend service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        # Try to fetch existing backend URL
        echo "Fetching Backend Service URL..."
        BACKEND_URL=$(gcloud run services describe backend --region asia-south1 --format 'value(status.url)' 2>/dev/null)
        
        if [ -z "$BACKEND_URL" ]; then
          echo "Error: Could not find service 'backend' in region asia-south1."
          echo "Please ensure the backend is deployed first."
          exit 1
        fi
        
        echo "Found Backend URL: $BACKEND_URL"
        
        gcloud run deploy frontend \
          --image gcr.io/$PROJECT_ID/frontend \
          --region asia-south1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars BACKEND_URL=$BACKEND_URL
    id: 'Deploy Frontend'

images:
  - 'gcr.io/$PROJECT_ID/frontend'
